### ISSUE TITLE
Come on now 

### ISSUE THREAD

**Issue by XFizzer** [Netstarv2/DropPartyPE#1]
Stop taking other people’s plugins https://github.com/HotshotHD/DropParty

**Comment by Netstarv2** [comment]
Dude check the codes. I took inspiration from him. But I added few other things like enable or disable pvp in one plugin added ability to drop custom enchants with piggy enchants and more. Pls dont judge a book by its cover.

**Comment by XFizzer** [comment]
I did check the code that’s why I called you out, all you did was added some color codes to the  messages, stop taking other people’s plugin it’s a piece of shit thing to do
